<script setup lang="ts">
import {
	computed, type StyleValue, 
} from 'vue'

import type { ProductModelDto } from '@/models/dto/products/model'
import { getDominatingColorStyle } from '@/utils/color'

const props = defineProps<{
	product: ProductModelDto
}>()

// @TODO: create function returning correct product link
const productLink = computed<string>(() => {
	return `/products/${props.product.autogeneratedSlug}-${props.product.id}`
})

const placeholderBackground = computed<StyleValue | undefined>(() => {
	const dominatingColor = props.product?.borderInfo?.dominatingColor

	return dominatingColor
		? `background: ${getDominatingColorStyle(dominatingColor)}`
		: undefined
})
</script>

<template>
	<v-card
		:to="productLink"
		hover
	>
		<v-img
			:src="product.thumbnailUrl"
			aspect-ratio="1"
			rounded="lg"
		>
			<template #placeholder>
				<div
					class="w-100 h-100"
					:style="placeholderBackground"
				/>
			</template>
		</v-img>

		<v-card-title class="text-subtitle-1">
			{{ product.name }}
		</v-card-title>

		<v-card-subtitle class="font-weight-bold opacity-100">
			{{ product.defaultDisplayedPriceFormatted }}
		</v-card-subtitle>

		<v-card-actions>
			<v-btn
				text="Add to cart"
			/>
		</v-card-actions>
	</v-card>
</template>

<style scoped>
.product-title {
	white-space: wrap;
}
</style>
