<script setup lang="ts">
import {
	computed, type StyleValue, 
} from 'vue'

import type { CategoryModelDto } from '@/core/models/dto/categories/model'
import { getDominatingColorStyle } from '@/core/utils/color'

const props = defineProps<{
	category: CategoryModelDto
}>()
// @TODO: create function returning correct category link
const categoryLink = computed<string>(() => {
	return `/categories/${props.category.autogeneratedSlug}-${props.category.id}`
})

const placeholderBackground = computed<StyleValue | undefined>(() => {
	const dominatingColor = props.category?.borderInfo?.dominatingColor

	return dominatingColor
		? `background: ${getDominatingColorStyle(dominatingColor)}`
		: undefined
})
</script>

<template>
	<v-card
		:to="categoryLink"
		hover
	>
		<v-img
			:src="category.thumbnailUrl"
			class="align-end text-white"
			gradient="to bottom, rgba(0,0,0,0), rgba(0,0,0,.6)"
			aspect-ratio="1"
			cover
		>
			<template #placeholder>
				<div
					class="w-100 h-100"
					:style="placeholderBackground"
				/>
			</template>

			<v-card-item>
				<v-card-title>
					{{ category.name }}
				</v-card-title>

				<v-card-subtitle v-if="category.productCount && category.productCount > 0">
					{{ category.productCount }} Product{{ category.productCount > 1 ? 's' : '' }}
				</v-card-subtitle>
			</v-card-item>
		</v-img>
	</v-card>
</template>
