<script setup lang="ts">
import { computed } from 'vue'

import type { CategoryModelDto } from '@/models/dto/categories/model'

const props = defineProps<{
	category: CategoryModelDto
}>()
// @TODO: create function returning correct category link
const categoryLink = computed<string>(() => {
	return `/categories/${props.category.autogeneratedSlug}`
})
</script>

<template>
	<router-link
		:to="categoryLink"
		class="text-decoration-none"
	>
		<v-card
			hover
			link
		>
			<v-img
				:src="category.thumbnailUrl"
				class="align-end text-white"
				gradient="to bottom, rgba(0,0,0,0), rgba(0,0,0,.5)"
				cover
			>
				<v-card-title class="d-flex justify-center">
					<div>{{ category.name }}</div>	
				</v-card-title>
			</v-img>
		</v-card>
	</router-link>
</template>
