<script setup lang="ts">
import {
	computed, type StyleValue, 
} from 'vue'

import type { CategoryModelDto } from '@/models/dto/categories/model'
import { getDominatingColorStyle } from '@/utils/color'

const props = defineProps<{
	category: CategoryModelDto
}>()
// @TODO: create function returning correct category link
const categoryLink = computed<string>(() => {
	return `/categories/${props.category.autogeneratedSlug}-${props.category.id}`
})

const placeholderBackground = computed<StyleValue | undefined>(() => {
	const dominatingColor = props.category?.borderInfo?.dominatingColor

	return dominatingColor
		? `background: ${getDominatingColorStyle(dominatingColor)}`
		: undefined
})
</script>

<template>
	<v-card
		:to="categoryLink"
		hover
	>
		<v-img
			:src="category.thumbnailUrl"
			class="align-end text-white"
			gradient="to bottom, rgba(0,0,0,0), rgba(0,0,0,.5)"
			aspect-ratio="1"
			cover
		>
			<template #placeholder>
				<div
					class="w-100 h-100"
					:style="placeholderBackground"
				/>
			</template>
			<v-card-title class="d-flex justify-center">
				<div>{{ category.name }}</div>	
			</v-card-title>
		</v-img>
	</v-card>
</template>
