import type {
	Category, CategoryImagePlaceholderColor, CategoryThumbnail, 
} from '../models/category'
import type { CategoryModelDto } from '../models/dto/categories/model'

function fromThumbnailDto(dto?: CategoryModelDto): CategoryThumbnail {
	return {
		thumbnailUrl: dto?.thumbnailUrl,
		hdThumnnailUrl: dto?.hdThumbnailUrl,
		imageUrl: dto?.imageUrl,
	}
}

function fromPlaceholderDto(dto?: CategoryModelDto): CategoryImagePlaceholderColor {
	const {
		red = 255,
		green = 255,
		blue = 255,
		alpha, 
	} = dto?.borderInfo?.dominatingColor ?? {}
	
	return {
		red,
		green,
		blue,
		alpha,
	}
}

export function fromCategoryModelDto(dto?: CategoryModelDto): Category {
	return {
		id: dto?.id?.toString() ?? '',
		name: dto?.name ?? '',
		slug: dto?.autogeneratedSlug ?? '',
		productCount: dto?.productCount ?? 0,
		description: dto?.description ?? '',
		thumbnail: fromThumbnailDto(dto),
		placeholder: fromPlaceholderDto(dto),
	}
}
