import type { ImageBorderInfoDto } from '@/core/models/dto/media'
import type {
	AltTranslationsDto,
	TranslationsDto, 
} from '@/core/models/dto/translations'

export type CategoryImageDetailsDto = {
	url?: string
	width?: number
	height?: number
}

export type CategoryModelDto = {
	id?: number
	parentId?: number
	orderBy?: number
	hdThumbnailUrl?: string
	thumbnailUrl?: string
	imageUrl?: string
	originalImageUrl?: string
	originalImage?: CategoryImageDetailsDto
	name?: string
	thumbnail?: CategoryImageDetailsDto
	translations?: TranslationsDto
	origin?: string
	url?: string
	autogeneratedSlug?: string
	customSlug?: string
	productCount?: number
	enabledProductCount?: number
	description?: string
	descriptionTranslated?: TranslationsDto
	enabled?: boolean
	productIds?: number
	seoTitle?: string
	seoTitleTranslated?: string
	seoDescription?: string
	seoDecriptionTranslated?: string
	alt?: AltTranslationsDto
	borderInfo?: ImageBorderInfoDto
}
